### ISSUE TITLE
invert option?

### ISSUE THREAD

**Issue by knausb** [sjmgarnier/viridisLite#1]
Hello,

Thank you for a neat new color ramp! As I've been using it I've found myself inverting the color ramp. For example, if I'm using the default color ramp and I have a lot of large values I get a lot of yellow, which I do not like. I can invert it manually with something like

```
viridisLite::viridis(n=10, alpha = 1, option = "D")[10:1]
```

But thought an invert option may be a nice feature for you to add to your next version? My two cents.

Thank you!
Brian

**Comment by sjmgarnier** [comment]
We added a direction parameter to the function in 403d3cc. This should do the trick.

**Comment by knausb** [comment]
Yay! Thank you!
