### ISSUE TITLE
viridisLite installed without data breaks viridis

### ISSUE THREAD

**Issue by jonathon-love** [sjmgarnier/viridisLite#17]
hi,

when doing lean system installs, where one doesn't need example data sets, we can install packages with:

```
R CMD INSTALL blah --no-data --no-help --no-demo --no-html
```

however in the case of viridisLite, doing this breaks the installation of viridis:

```
Error : 'viridis.map' is not an exported object from 'namespace:viridisLite'
Error: unable to load R code in package 'viridis'
Execution halted
```

is it possible to rejig this so `viridis.map` is still available when `viridisLite` is installed with `--no-data`? i.e. by placing the data in the `inst` folder, rather than (or in addition to) the `data` folder?

quite a few times over the years, i've had to add special code to catch when viridisLite is being installed, and treat it differently.

with thanks

**Comment by jens-maus** [comment]
@jonathon-love Can you please share your information with us how you worked around that issue as it seems other people are running into the same problem here.

**Comment by jens-maus** [comment]
I actually found a procedure that worked here with R 4.0.2:

1. Download `viridisLite_0.3.0.tar.gz` and unarchive it.
2. Execute `R CMD INSTALL --data viridisLite`
3. Download `viridis_0.5.1.tar.gz` and unarchive it
4. Execute `R CMD INSTALL viridis`

This actually seem to have worked nicely.

**Comment by mverkerk** [comment]
Hi,

I got the same error with an R installation on a network drive (NFS4).

When I tried installing on the same machine at a local disk folder, I didn't get the error message and installation of viridis went without problems.

Best wishes!

**Comment by sjmgarnier** [comment]
@jonathon-love I finally have some time to look into this. I understand the issue but I'm not certain what the best way would be to address it. Putting the data in inst means that it is not exportable (unless I'm missing something). It would therefore need to be read every time the function is called, which is not ideal either.

**Comment by jonathon-love** [comment]
thanks for taking a look. could you simply do:

```
viridis.map <- read.csv(system.file(...))
```

in your .R code? i *think* this step would be performed at compile time, but i'm not completely sure.

alternatively, what if we just convert the .csv file (or whatever this is) into a .R file?

```
viridis.map <- data.frame(c(4,7,35,8,2,4, ...))
```

i'm happy to write a little script that will do this.

let me know what you think.

cheers

jonathon

**Comment by sjmgarnier** [comment]
@jonathon-love The first solution is precisely what I'm trying to avoid, unfortunately. Unless I'm mistaken, this approach would not export the data, which means that people wanting to use, for instance, `viridisLite::viridis()` would be thrown an error at (which is the case inside many of the packages depending on `viridisLite`, a smart approach to avoid loading too many unnecessary things in memory). Besides, this would not work either if someone decides to use, says, `--no-inst` for the same reason that you use `--no-data`. 

The second approach is ugly :-) but it may work. I will give it a try.

**Comment by sjmgarnier** [comment]
@jonathon-love The latest version on the master and develop branches should fix the issue. Let me know if that's not the case.

**Comment by jonathon-love** [comment]
works for me! thanks!
