### ISSUE TITLE
Issue with package "viridis"

### ISSUE THREAD

**Issue by ghost** [sjmgarnier/viridisLite#8]
I might be missing something here... but since the most recent changes to viridisLite I have been unable to install the package "viridis" - I get the following error "Error : object ‘cividis’ is not exported by 'namespace:viridisLite'". This wasn't an issue a week ago so I am assuming that it is the recent changes. Apologies if I have made a mistake!

**Comment by sjmgarnier** [comment]
@hferg Did you update viridisLite as well?

**Comment by ghost** [comment]
@sjmgarnier I thought that I had, but it appears that I hadn't! Many apologies, and thanks!

**Comment by sjmgarnier** [comment]
@hferg No problem.
